### ISSUE TITLE
Sub-optimal pruning of "contested" taxa

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/otcetera#13]
So I am having a subproblem problem. The situation:

There is a backbone Class-level tree that samples families, except the tips are labelled with exemplar genera (i.e. 1 per family). One genus in that tree, X, is non-monophyletic in another tree. The other tree happens to be a phylogeny of the family, Y, which is monophyletic (it is currently a recognized subproblem).

It seems clear that the subtree Y is equivalent to the tip X in the family-sampled Class-level tree. However, because X is contested, it is pruned from the Class-level tree. No other existing tree has sampling that spans Y and not-Y , so there is no other connection of Y to the other families, and so Y ends up being far deeper in the synth tree, well away from its sister families in the Class-level tree. [The situation appears more egregious because the Order in which Y is placed in OTT is not monophyletic (it is not monophyletic), so Y goes back deeper still.]

This is one of those cases that argue for the "map deeper" option that treemachine used to use: the Class-level tree clearly is sampling families, but is labelled with genera.

I'm not sure this is a problem in your mind (because the monophyly of the family comes from another tree; but it is not contested by any tree, either), and/or if you are willing to fix it (or how long that might take).

In case you want to take a look, the class-level tree is pg_420_522, and the family tree is ot_140_1. The non-monophyletic genus sampled in the former is 322277 (Phalacrocorax), and the family is 969838 (Phalacrocoracidae).

Ways I can think of to possibly address this:

1. Map taxa deeper in the curator. But this is undesirable because then the tree does not match the publication.
2. More trees! Just one extra tree that samples (non-contested) from the relevant families would make the problem go away. This isn't very helpful, though, as 1) trees may not be available and 2) recognizing that this problem exists is not straightforward.
3. [the proposed otcetera solution] Keep track of the contested-status of taxonomic parents of contested taxa. If, in the above example, X is non-monophyletic but "descendants" of X definitely belong in (uncontested) Y, then a tree sampling tip X has something to say about the placement of Y. It seems that this parent-tracking exists for the uncontested taxa (e.g. the Sauria tree [pg_2573](https://tree.opentreeoflife.org/curator/study/view/pg_2573/?tab=trees), which is reflected in subproblems spanning all of the relevant taxonomic nodes).

**Comment by josephwb** [comment]
I see this option is considered in the [writeup](http://phylo.bio.ku.edu/ot/summarizing-taxonomy-plus-trees.pdf).

**Comment by mtholder** [comment]
just adding links, as I look at this.
  Class-level: https://tree.opentreeoflife.org/curator/study/view/pg_420/?tab=trees&tree=tree522
  Family: https://tree.opentreeoflife.org/curator/study/view/ot_140/?tab=trees&tree=tree1

**Comment by mtholder** [comment]
I'm not exactly sure what the problem is. Perhaps my docs are out of date. When I moved to expanding the nonterminal tips to exemplars, I no longer prune these tips when they map to contested taxa. So the tip is in there...

More details for this case:

  1. Phalacrocorax (ott322277) is not monophyletic in https://tree.opentreeoflife.org/curator/study/view/ot_140/?tab=trees&tree=tree1
because of *Leucocarbo* species being scattered within it.  So `otcetera` does not export a subproblem for this taxon.

  2. It's parent, Phalacrocoracidae (ott969838) is uncontested  So the ott969838 subproblem is emitted. It has:
    1. All of study ot_140_1 (the family level tree). 
    2. a trivial tree from pg_420_522. That tree just had one tip mapped to Phalacrocorax. So, the new expansion of non-terminal taxon labelled tips (implemented as the tool that does steps 2.5 and 2.6 in the docs) replaces that mapped tip with a polytomy of all of the members of Phalacrocorax which are sampled (which turns out to just be those in ot_140_1)
    3. the taxonomy.
  This is actually a very easy subproblem because the structure provided by the taxonomy is contradict by ot_140_1, and no other tree contributes phylogenetic info. So the solution for this subproblem should just be the tree from ot_140_1.

  3. After resolving that, `otcetera` has resolved the polytomy in the expanded form of `pg_420_522` in favor of monophyly of Phalacrocoracidae. Any tree that has an edge that exits from this uncontested taxon, will have that edge remapped to ott969838, the subproblem ID. The tree ot_140_1 does not have any more taxa, so it does not contribute deeper. However, pg_420_522 did have an expanded polytomy (which was just resolved). So internally in `otcetera` the edge that resolves that polytomy is now resolved and labeled ott969838

  4. Apparently Pelicaniformes is contested, so there is no subproblem for it.

  5. The next uncontested ancestor is Neognathae, known to its friends as ott241846.  There are 7 sources of phylogenetic info, and the third tree is from pg_420_522.tre it has the fragment of `((ott443646,ott969838),ott452462)` which is "((Anhingidae,Phalacrocoracidae),Sulidae)". This (I believe) the correct remapping of the ((Anhinga,Phalacrocorax),Morus) clade in the source tree.


So, I think that the decomposition is doing what you want. Maybe I'm missing something.

**Comment by mtholder** [comment]
note that https://github.com/OpenTreeOfLife/reference-taxonomy/issues/132 refers to these taxa, but I don't think that there is really a problem here...

**Comment by josephwb** [comment]
Apologies: this seems to be a problem on our end (i.e. processing of your output). You indeed have:
```
...(((443646,969838),452462),452471)...
```
whereas we have:
```
...((452462,443646),452471)...
```
Keeping this open while I track down whether this is 1) an issue with file versions or 2) a bug.

**Comment by josephwb** [comment]
Hold on: when I ran the decomposition myself, I got:
```
...((ott443646),ott452462),ott452471)...
```
These are the files we have been using. We are using the same source newicks, so I am baffled...

**Comment by josephwb** [comment]
This is how I run the decomposition:
```bash
#!/bin/sh

OTT_TAX_TREE="Filtered_OTT_taxonomy.tre"
TAX_TREE="Pruned_filtered_OTT_taxonomy.tre"
TREE_DIR="mappedShallowTrees"
STUDY_RANKS="tree-ranking_original.txt"
OUT_DIR="Fixed-subprobs_original-order_JWB" 
echo "\nPruning taxonomy tree $OTT_TAX_TREE...\n"
otc-prune-taxonomy $OTT_TAX_TREE $TREE_DIR/*.tre > $TAX_TREE

# make directory for output
mkdir $OUT_DIR

echo "\nFinding subproblems...\n"
time otc-uncontested-decompose -e$OUT_DIR $TAX_TREE -f$STUDY_RANKS

# get rid of 'empty' files contain only TAXONOMY (so, 1 line)
# delete both the ottXXX.tre and ottXXX-tree-names.txt files
counter=0;
cd $OUT_DIR
NUM_FILES=`ls *-tree-names.txt | wc -l`
echo "\nChecking $NUM_FILES generated files to see if they contain TAXONOMY only..."
for i in *-tree-names.txt; do
    LINE_COUNT=`wc -l < $i`;
    if [ $LINE_COUNT = "1" ]; then
        OTTID=`echo $i | cut -d '-' -f 1`
        #echo "Removing files associated with: $OTTID."
        rm $OTTID.tre $OTTID-tree-names.txt
        counter=$((counter+1))
    fi
done
cd ..
echo "Deleted files associated with $counter unsampled taxa!"
```
Could the issue be:
```
otc-prune-taxonomy $OTT_TAX_TREE $TREE_DIR/*.tre > $TAX_TREE
```
i.e. the pre-pruning of taxonomy? Running both permutations; will see soon.

**Comment by josephwb** [comment]
Nope; I get the same result n omatter what.

**Comment by mtholder** [comment]
Commenting from a phone...
I'm using the make in the supertree of otcetera. That uses the new tool to  expand tips mapped to non terminal taxa. See the Makefile. Sorry for the brevity.

**Comment by mtholder** [comment]
I've cleaned up the docs of the `supertree` subdirectory - adding a README.md to each subdirectory to explain what is supposed to end up there, and how it is created.  
https://github.com/OpenTreeOfLife/otcetera/blob/master/supertree/README.md#usage is probably the best place to start.

It think that, following those instructions will help you generate the subproblems in the same way that I am generating them.

**Comment by josephwb** [comment]
Got this working now, so closing.
